name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      # Step 3: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Set up SSH (ensure you have a private key stored in GitHub Secrets)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Deploy application to Azure VM
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no username@your-vm-ip "sudo apt-get update && sudo apt-get install -y nginx"
          
          # Copy application files (if needed)
          # scp -o StrictHostKeyChecking=no -r * username@your-vm-ip:/var/www/html/
          
          # Restart NGINX to apply changes
          ssh -o StrictHostKeyChecking=no username@your-vm-ip "sudo systemctl restart nginx"
