name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v2

      # Step 3: Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Deploy application to Azure VM
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no username@20.5.194.56 "sudo apt-get update && sudo apt-get install -y nginx"
          
          # Copy application files (if needed)
          # scp -o StrictHostKeyChecking=no -r * azureuser@20.5.194.56:/var/www/html/
          
          # Restart NGINX to apply changes
          ssh -o StrictHostKeyChecking=no azureuser@y20.5.194.56 "sudo systemctl restart nginx"
