name: Deploy Nginx to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name:  Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: 'sp'

      - name: Deploy to Azure VM
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_VM_IP }}
          package: .

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
