name: Deploy Nginx to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js (Optional for frontend apps)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
       
      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
